# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Study3_ImagePicker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Study3_ImagePicker
  pod 'SnapKit', '~> 5.0.0'
  target 'Study3_ImagePickerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Study3_ImagePickerUITests' do
    # Pods for testing
  end

end
