# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Instagram_Light' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instagram_Light
  pod 'SnapKit'
  target 'Instagram_LightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Instagram_LightUITests' do
    # Pods for testing
  end

end
